### ISSUE TITLE
`Worker` should be `web` in Procfile

### ISSUE THREAD

**Issue by max810** [michaelkrukov/heroku-python-script#2]
So, I was developing a simple Telegram bot with Webhooks and your repo came in handy, I appreciate that. But I kept getting **"h14"** error, despite following all the steps in README. So basically Heroku refused to assign dyno to my process, I tried both `heroku ps:scale worker=1` and changing it manually from dashboard. Logs looked like this:
![image](https://user-images.githubusercontent.com/29955120/48977232-561ce280-f09f-11e8-87c9-1d888f3368c9.png)

Luckily, I found [this post](https://github.com/python-telegram-bot/python-telegram-bot/issues/505#issuecomment-273476061), which explained everything. After changing `worker` to `web` in my Procfile, bot finally started receiving requests, like this:
![image](https://user-images.githubusercontent.com/29955120/48977249-a5fba980-f09f-11e8-8762-a55b474e310e.png)

As you can see, it has nothing to do with the bot itself, because in **both** cases the app was launched successfully (look at "my comment" in logs).

I am not entirely sure this wasn't my fault, but it looks like it would be a good idea to at least mention `web` worker type in README.

**Comment by michaelkryukov** [comment]
Yes, I will add that. Thanks
