### ISSUE TITLE
Code 502 shows what?

### ISSUE THREAD

**Issue by Jainu-s** [michaelkrukov/heroku-python-script#5]
![herokulogs](https://user-images.githubusercontent.com/59506207/93494339-8e537c00-f92a-11ea-8a9b-0d758fe65559.png)

I followed your instructions and It was successfully deployed on Heroku. When I run the code " heroku ps:scale worker=1 " and it displayed " Scaling dynos... done, now running worker at 1:Free " and when I enter " heroku logs --tail "  I got the  logs showing code 502 something... I have taken a screenshot and attached it to this. Please tell me whether my application is running or not. I have scheduled all the tasks at a particular time with a " schedule module " in python code.

**Comment by michaelkryukov** [comment]
You get `503 Service Unavailable ` when trying to make HTTP requests to the server that doesn't really run any web server. If you are running some script, that is not server, you can't make requests. Following your logs, your app is running. 

Be careful though:

> If an app has a free web dyno, and that dyno receives no web traffic in a 30-minute period, it will sleep. In addition to the web dyno sleeping, the worker dyno (if present) will also sleep.
>
> Free web dynos do not consume free dyno hours while sleeping.

https://devcenter.heroku.com/articles/free-dyno-hours#dyno-sleeping
