### ISSUE TITLE
Do worker dynos not consume dyno hours?

### ISSUE THREAD

**Issue by DavisAndn** [michaelkrukov/heroku-python-script#6]
Firstly, thank you for providing this useful repo. I noticed after setting up the program that dyno hours are not being used up by the process. Do only web dynos(and not worker dynos) use dyno hours?

**Comment by michaelkryukov** [comment]
I'm pretty sure every dyno consume dyno hours (https://www.heroku.com/dynos, https://devcenter.heroku.com/articles/usage-and-billing#computing-usage)

**Comment by DavisAndn** [comment]
I've realized there's a 24-36h delay in the update of dyno hours used. Wasn't able to find this info anywhere but maybe it'll help the next person who has this same doubt
